# Generated by Django 2.1.1 on 2018-09-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='tipoNotificacion',
            field=models.TextField(choices=[('Email', 'Email'), ('Telefono', 'Telefono'), ('Ambos', 'Ambos'), ('NINGUNO', 'Ninguno')], default='Ambos'),
        ),
    ]
