# Generated by Django 2.1.2 on 2018-10-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_noticia_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='url',
        ),
    ]
