# Generated by Django 2.1.1 on 2018-10-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='email',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='telefono',
        ),
        migrations.AddField(
            model_name='envio',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Cliente'),
        ),
    ]
