# Generated by Django 2.1.2 on 2018-10-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20181029_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='tipoNotificacion',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
