# Generated by Django 2.1.2 on 2018-10-30 13:55

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20181029_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='fechaLimite',
            field=models.DateField(validators=[web.models.no_past]),
        ),
    ]
