# Generated by Django 2.1.2 on 2018-10-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_peticion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
    ]
