# Generated by Django 2.1.2 on 2018-10-10 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_noticia_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='archivos')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='aviso',
            old_name='fecha',
            new_name='fechaLimite',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='cliente',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='peticion',
            old_name='cliente',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen',
        ),
        migrations.AddField(
            model_name='envio',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='envio',
            name='peticion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Peticion'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Usuario',
        ),
        migrations.AddField(
            model_name='recibo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Usuario'),
        ),
    ]
