# Generated by Django 2.1.2 on 2018-10-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_usuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias_usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Noticia')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Usuario')),
            ],
        ),
    ]
