# Generated by Django 2.1.2 on 2018-10-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_noticias_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias_usuarios',
            name='noticia',
        ),
        migrations.RemoveField(
            model_name='noticias_usuarios',
            name='usuario',
        ),
        migrations.AddField(
            model_name='noticias_usuarios',
            name='noticia_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='noticias_usuarios',
            name='usuario_id',
            field=models.IntegerField(null=True),
        ),
    ]
